Repository knative-extensions/kn-plugin-sample, pull requests merged in 2021-02, with the labels that each got.

#1 Fix existing woke warnings
  hack/README.md
Labels: approved, cla: yes, lgtm, size/XS

#4 chore: Add lint config
  .golangci.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#5 add CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
