Repository knative-extensions/kn-plugin-sample, pull requests merged in 2021-03, with the labels that each got.

#9 fix: Fix script's permissions
  hack/release.sh
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#11 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#6 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XL

#8 [Automated] Fix misspellings
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#13 add missing LICENSE
  LICENSE
Labels: approved, cla: yes, lgtm, size/L

#14 Update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#17 chore: Update Knative Client to v0.21.0
  go.mod
  go.sum
  hack/build.sh
  hack/global_vars.sh
  internal/command/version_test.go
  third_party/VENDOR-LICENSE/github.com/mitchellh/go-homedir/LICENSE
  third_party/VENDOR-LICENSE/github.com/spf13/cobra/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/spf13/pflag/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/client/pkg/kn/plugin/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/kn-plugin-sample/LICENSE
  vendor/gotest.tools/v3/LICENSE
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/internal/assert/assert.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/difflib/LICENSE
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/diff.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/knative.dev/client/pkg/kn/plugin/verify.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#15 [Automated] Format markdown
  BLUEPRINT.md
  hack/README.md
Labels: approved, cla: yes, lgtm, size/M

#16 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
