Repository knative-extensions/kn-plugin-sample, pull requests merged in 2021-04, with the labels that each got.

#26 Update build.sh
  hack/build.sh
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#25 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#28 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm
