Repository knative-extensions/kn-plugin-sample, pull requests merged in 2022-04, with the labels that each got.

#48 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/M, skip-review

#53 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#52 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: size/XS, approved, lgtm

#55 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
